spring:
  application:
    name: notification-service
  config:
    import: configserver:http://config-server:8888
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    topic:
      notifications: ${KAFKA_TOPIC_NOTIFICATIONS}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}